[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
nutt-web = "0.0.0"
nutt-web-macro = "0.1.3"
tokio = {version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"]}
serde = {version = "1.0.210", features = ["derive"]}